name: Continuous deployment workflow

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
    - name: Git Config
      run: |
        git config --global user.email "andyrosete17@gmail.com"
        git config --global user.name "andyrosete17"
    - name: Install
      uses: npm install
    - name: Build
      uses: npm run build
    - name: Deploy
      uses: npm run deploy -- -r git@github.com:andyrosete17/DeliveryTask2.git
