name: Continuous deployment workflow

on:
  push:
    branches:
      - master
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{secrets.SSH_PRIVATE_KEY_II}}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
    - name: Git Config
      run: |
        git config --global user.email "cd-user@rick-and-morty.com"
        git config --global user.name "cd-user"
    - name: Install
      run: npm ci --save --legacy-peer-deps
    - name: Build
      run: npm run build
    - name: Deploy
      run: npm run deploy -- -r git@github.com:andyrosete17/DeliveryTask2.git
